version: '3'

services:
  next-airbnb2.0:
    container_name: next-airbnb2.0
    build:
      context: ./next-airbnb2.0
      dockerfile: dev.Dockerfile

    # Set envrionment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./next-airbnb2.0/src:/app/src
      - ./next-airbnb2.0/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    driver: bridge
